# Generated by Django 5.1.3 on 2024-11-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_completions_lessons_alter_completions_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
