# Generated by Django 5.1.3 on 2024-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
