# Generated by Django 5.1.3 on 2024-11-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_users_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completions",
            name="lessons",
        ),
        migrations.RemoveField(
            model_name="completions",
            name="students",
        ),
        migrations.AddField(
            model_name="completions",
            name="enroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.enroll",
            ),
        ),
    ]
