# Generated by Django 5.1.3 on 2024-11-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_completions_lessons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completions",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
